name: SchoolManagementApi
on:
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: School Management Rest Api
      env:
        HEROKU_API_KEY: ${{secrets.SECRET_API_kEY}}
        APP_NAME: school-mgt-api
      run: |
        docker build -t school-mgt-api .
        docker tag school-mgt-api registry.heroku.com
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
