name: SchoolManagementApi
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: School Management Rest Api
      env:
        HEROKU_API_KEY: ${{secrets.SECRET_API_KEY}}
        APP_NAME: ${{ secrets.SECRET_APP_NAME }}
      run: |
        docker login --username=_ --password=$SECRET_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
